name: VDoc
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install mdbook
      run: |
        pushd /tmp
        mkdir mdbook
        curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.14/mdbook-v0.4.14-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=./mdbook
        echo `pwd`/mdbook >> $GITHUB_PATH        
        popd
    - name: Install v
      run: |
        pushd /tmp
        git clone --depth 1 https://github.com/vlang/v
        cd v
        make
        echo `pwd` >> $GITHUB_PATH
        popd
    # - name: Generate V Docs
    #   run: |
    #     # v doc twinactions/ -f md  -no-timestamp -comments -o docs/src/v
    # - uses: EndBug/add-and-commit@v9
    #   with:
    #     default_author: github_actions    
    - name: Generate MDBOOK
      run: |
        # v doc twinactions/ -f md  -no-timestamp -comments -o docs/src/v
        bash doc.sh
        cd docs
        git worktree add gh-pages
        git config user.name "Deploy from CI"
        git config user.email ""
        cd gh-pages
        # Delete the ref to avoid keeping history.
        git update-ref -d refs/heads/gh-pages
        rm -rf *
        mv ../book/* .
        git add .
        git commit -m "Deploy $GITHUB_SHA to gh-pages"
        git push --force --set-upstream origin gh-pages        
